server:
  port: 8081

jwt:
  secret: 'lallavepa'

media:
  location: mediafiles

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pitufos
    username: postgres
    password: m3ta
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      enabled: true

